// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1LvijWFjTBmXw4WHzTfy6rNc7lCSQ8HY',
    appId: '1:1052165853388:web:a6130d32d3b17827e67269',
    messagingSenderId: '1052165853388',
    projectId: 'chat-app-9f200',
    authDomain: 'chat-app-9f200.firebaseapp.com',
    storageBucket: 'chat-app-9f200.appspot.com',
    measurementId: 'G-N7LTZ6VLW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-rhB3SzISGzR7prwRWSMJP6Dd2gnOizw',
    appId: '1:1052165853388:android:41ee8648e1a20f5ee67269',
    messagingSenderId: '1052165853388',
    projectId: 'chat-app-9f200',
    storageBucket: 'chat-app-9f200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq6qQ3s0wFbPd2_xYiqiar4CVHBZl6cGg',
    appId: '1:1052165853388:ios:8b8087e58e37e0d6e67269',
    messagingSenderId: '1052165853388',
    projectId: 'chat-app-9f200',
    storageBucket: 'chat-app-9f200.appspot.com',
    iosClientId: '1052165853388-opk5gh8rdr8dd2os6ecun26uesvn51vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq6qQ3s0wFbPd2_xYiqiar4CVHBZl6cGg',
    appId: '1:1052165853388:ios:8b8087e58e37e0d6e67269',
    messagingSenderId: '1052165853388',
    projectId: 'chat-app-9f200',
    storageBucket: 'chat-app-9f200.appspot.com',
    iosClientId: '1052165853388-opk5gh8rdr8dd2os6ecun26uesvn51vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarchat',
  );
}
